
import java.awt.GridLayout;
import java.util.Calendar;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WarisArjuna
 */
public class FormHitungHari extends javax.swing.JFrame {

    /**
     * Creates new form FormHitungHari
     */
    public FormHitungHari() {
        initComponents();
        setLocationRelativeTo(null); 
        
        // === Ubah layout panelBottom ===
        panelBottom.setLayout(new java.awt.GridLayout(3, 1));
        panelBottom.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Perhitungan"));
        
        // === Panggil helper functions ===
        HelperSinkronisasi.setModelSpinnerTahun(spnTahun);
        HelperSinkronisasi.sinkronSpinnerKeKalender(spnTahun, cbBulan, jCalendar);
        HelperSinkronisasi.sinkronKalenderKeSpinner(jCalendar, spnTahun, cbBulan);
        HelperSinkronisasi.sinkronComboBoxKeKalender(cbBulan, jCalendar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        lblBulan = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox<>();
        lblTahun = new javax.swing.JLabel();
        spnTahun = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jCalendar = new com.toedter.calendar.JCalendar();
        btnHitung = new javax.swing.JButton();
        btnSelisih = new javax.swing.JButton();
        panelSelisih = new javax.swing.JPanel();
        lblTanggal1 = new javax.swing.JLabel();
        lblTanggal2 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        panelBottom = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        lblHasil = new javax.swing.JLabel();
        lblHariPertama = new javax.swing.JLabel();
        lblHariTerakhir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perhitungan Hari");
        setBackground(new java.awt.Color(225, 235, 245));
        setMaximumSize(new java.awt.Dimension(750, 550));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 550));

        panelTop.setBackground(new java.awt.Color(245, 245, 247));
        panelTop.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 10, 15, 10));
        panelTop.setPreferredSize(new java.awt.Dimension(750, 80));

        lblJudul.setBackground(new java.awt.Color(0, 51, 102));
        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(0, 51, 102));
        lblJudul.setText("Aplikasi Perhitungan Hari");
        panelTop.add(lblJudul);

        getContentPane().add(panelTop, java.awt.BorderLayout.PAGE_START);

        panelCenter.setBackground(new java.awt.Color(240, 245, 250));
        panelCenter.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panelCenter.setPreferredSize(new java.awt.Dimension(750, 350));

        lblBulan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBulan.setText("Bulan :");

        cbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cbBulan.setPreferredSize(new java.awt.Dimension(180, 30));

        lblTahun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTahun.setText("Tahun :");

        spnTahun.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Atau Pilih di Kalender :");

        jCalendar.setPreferredSize(new java.awt.Dimension(150, 130));

        btnHitung.setText("Hitung Hari");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnSelisih.setText("Selisih");

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCenterLayout.createSequentialGroup()
                                .addComponent(lblBulan)
                                .addGap(138, 138, 138)
                                .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCenterLayout.createSequentialGroup()
                                .addComponent(lblTahun)
                                .addGap(134, 134, 134)
                                .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(btnHitung)
                        .addGap(39, 39, 39)
                        .addComponent(btnSelisih))
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblBulan))
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCenterLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblTahun))
                    .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHitung)
                    .addComponent(btnSelisih))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        lblTanggal1.setText("Tanggal 1");

        lblTanggal2.setText("Tanggal 2");

        javax.swing.GroupLayout panelSelisihLayout = new javax.swing.GroupLayout(panelSelisih);
        panelSelisih.setLayout(panelSelisihLayout);
        panelSelisihLayout.setHorizontalGroup(
            panelSelisihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelisihLayout.createSequentialGroup()
                .addGroup(panelSelisihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSelisihLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSelisihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTanggal1)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSelisihLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblTanggal2)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        panelSelisihLayout.setVerticalGroup(
            panelSelisihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelisihLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTanggal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(lblTanggal2)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        getContentPane().add(panelSelisih, java.awt.BorderLayout.LINE_END);

        panelBottom.setBackground(new java.awt.Color(210, 225, 240));
        panelBottom.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 15, 15));
        panelBottom.setPreferredSize(new java.awt.Dimension(750, 120));
        panelBottom.setLayout(new java.awt.GridLayout());

        lbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl.setText("Hasil Hitung :");
        panelBottom.add(lbl);

        lblHasil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHasil.setForeground(new java.awt.Color(0, 153, 51));
        lblHasil.setText("0");
        panelBottom.add(lblHasil);

        lblHariPertama.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHariPertama.setText("Hari Pertama : ");
        panelBottom.add(lblHariPertama);

        lblHariTerakhir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHariTerakhir.setText("Hari Terakhir :");
        panelBottom.add(lblHariTerakhir);

        getContentPane().add(panelBottom, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // === Validasi Input ===
        if (cbBulan.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, 
                    "Silakan pilih bulan terlebih dahulu!",
                    "Peringatan", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int tahun = (int) spnTahun.getValue();
        if (tahun < 1900 || tahun > 2100) {
            JOptionPane.showMessageDialog(this, 
                    "Tahun harus antara 1900 dan 2100!",
                    "Peringatan", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // === Ambil data bulan dan tahun ===
        int bulan = cbBulan.getSelectedIndex() + 1; // Januari = 1, dst

        try {
            // === Hitung jumlah hari menggunakan LocalDate ===
            java.time.LocalDate tanggal = java.time.LocalDate.of(tahun, bulan, 1);
            int jumlahHari = tanggal.lengthOfMonth();

            java.time.DayOfWeek hariPertama = tanggal.getDayOfWeek();
            java.time.DayOfWeek hariTerakhir = tanggal.withDayOfMonth(jumlahHari).getDayOfWeek();

            // === Format nama hari agar rapi (Indonesia) ===
            java.time.format.TextStyle style = java.time.format.TextStyle.FULL;
            java.util.Locale localeID = new java.util.Locale("id", "ID");

            String hariAwal = hariPertama.getDisplayName(style, localeID);
            String hariAkhir = hariTerakhir.getDisplayName(style, localeID);

            // === Tampilkan hasil ===
            lblHasil.setText(jumlahHari + " hari");
            lblHariPertama.setText("Hari pertama: " + hariAwal);
            lblHariTerakhir.setText("Hari terakhir: " + hariAkhir);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat menghitung hari: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHitungHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSelisih;
    private javax.swing.JComboBox<String> cbBulan;
    private com.toedter.calendar.JCalendar jCalendar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHariPertama;
    private javax.swing.JLabel lblHariTerakhir;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblTanggal1;
    private javax.swing.JLabel lblTanggal2;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelSelisih;
    private javax.swing.JPanel panelTop;
    private javax.swing.JSpinner spnTahun;
    // End of variables declaration//GEN-END:variables
}
